name: secure_vault
description: A secure file encryption and decryption app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Supabase
  supabase_flutter: ^2.0.0

  # Encryption
  encrypt: ^5.0.3
  pointycastle: ^3.7.3

  # File operations
  file_picker: ^10.3.6
  share_plus: ^12.0.1
  path_provider: ^2.1.1

  # Secure storage
  flutter_secure_storage: ^10.0.0-beta.4

  # Permissions
  permission_handler: ^12.0.1

  # UI
  google_fonts: ^6.1.0

  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#5DBE7A"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
